version: '3'

services:
  postgres:
    image: postgres:17.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=s3cr3tp455w0rd
      - POSTGRES_DB=orders
  solution:
    image: solution:latest
    environment:
      - PG_HOST=postgres
